### ISSUE TITLE
在vite中该如何进行配置使用呢

### ISSUE THREAD

**Issue by 934556826** [baozouai/babel-plugin-enhance-log#2]
项目是vite3加vue3，没有babel.config.js这个文件，不知如何配置

**Comment by baozouai** [comment]
@934556826 你好，提供个最小工程，我看能否配置

**Comment by baozouai** [comment]
@934556826 已开源vite-plugin-enhance-log，详情请看https://github.com/baozouai/vite-plugin-enhance-log
