### ISSUE TITLE
已经使用了，很好用，美中不足

### ISSUE THREAD

**Issue by JiaErGen** [baozouai/babel-plugin-enhance-log#3]
已经使用了，很好用，但是美中不足的是点击日志文件输出的文件位置不能跳转到指定行，只能跳转到指定文件，使用的vscode。希望点击跳转的时候直接跳转到指定文件的指定行数。

文件位置输出：src/pages/Resume/ResumeDetails/indexClass.tsx:

**Comment by JiaErGen** [comment]
补充一点，我是在react-native 上使用的

**Comment by baozouai** [comment]
> 已经使用了，很好用，但是美中不足的是点击日志文件输出的文件位置不能跳转到指定行，只能跳转到指定文件，使用的vscode。希望点击跳转的时候直接跳转到指定文件的指定行数。
> 
> 文件位置输出：src/pages/Resume/ResumeDetails/indexClass.tsx:

<img width="1102" alt="image" src="https://github.com/baozouai/babel-plugin-enhance-log/assets/33510001/7b2cfd10-ca2f-4aab-bff8-af8a6e5cd8f6">
<img width="564" alt="image" src="https://github.com/baozouai/babel-plugin-enhance-log/assets/33510001/656baa59-4d61-43ef-8000-fc3b6e57a278">


我看是可以跳到指定行呀，是不是你哪里配置有问题，提供下最小复现demo我看看，或者你把项目拉下来，里面有个playgrounds，可以看看我写的demo

<img width="236" alt="image" src="https://github.com/baozouai/babel-plugin-enhance-log/assets/33510001/db77102a-7528-4c73-8ee3-3b3ddb61083b">
@JiaErGen

**Comment by baozouai** [comment]
> 补充一点，我是在react-native 上使用的

rn我确实没跑过，web是没问题的，贴下配置看看

**Comment by JiaErGen** [comment]
<img width="724" alt="image" src="https://github.com/baozouai/babel-plugin-enhance-log/assets/26734029/49b74ade-d55f-4ecf-86eb-a34b39be4bf5">

**Comment by JiaErGen** [comment]
<img width="720" alt="image" src="https://github.com/baozouai/babel-plugin-enhance-log/assets/26734029/999c37d6-b6b9-455b-a9e4-ebc624884e16">

**Comment by JiaErGen** [comment]
理论上来说，把行数哪个输出放到和文件位置输出后面应该就稳了，现在是行数和文件位置分开了

**Comment by baozouai** [comment]
> 理论上来说，把行数哪个输出放到和文件位置输出后面应该就稳了，现在是行数和文件位置分开了

我懂你意思了，行数是没问题，问题是在于rn的log是在控制台。。之前sourcemap的功能是因为浏览器提供了，所以能跳过去，但rn是在控制台，我看看咋弄

**Comment by JiaErGen** [comment]
> 

是的

**Comment by baozouai** [comment]
> > 
> 
> 是的

那敬请关注，我看看咋弄，别忘了给个star，哈哈哈

**Comment by JiaErGen** [comment]
> > > 
> > 
> > 
> > 是的
> 
> 那一关注，我看看咋弄，别忘了给个明星，哈

肯定啊，这个对RN来说还是很好用

**Comment by baozouai** [comment]
> > > > 
> > > 
> > > 
> > > 是的
> > 
> > 
> > 那一关注，我看看咋弄，别忘了给个明星，哈
> 
> 肯定啊，这个对RN来说还是很好用

好用就行，也不费我投入精力，这是对我的最大鼓励和支持~

**Comment by JiaErGen** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 那一关注，我看看咋弄，别忘了给个明星，哈
> > 
> > 
> > 肯定啊，这个对RN来说还是很好用
> 
> 好用就行，也不费我投入精力，这是对我的最大鼓励和支持~

大佬给力，我认为是RN开发必备的神器

**Comment by JiaErGen** [comment]
可以在node项目中使用打印试一下，输出也是在vscode控制台，RN环境比较麻烦

**Comment by baozouai** [comment]
> 可以在node项目中使用打印试一下，输出也是在vscode控制台，RN环境比较麻烦

我也是这么想的，虽然我有rn项目，哈哈

**Comment by JiaErGen** [comment]
<img width="865" alt="image" src="https://github.com/baozouai/babel-plugin-enhance-log/assets/26734029/80fe64f2-3735-4ba2-9f95-31bb40332ee5">
用这个方案可以直接跳到指定行

**Comment by baozouai** [comment]
> <img alt="image" width="865" src="https://user-images.githubusercontent.com/26734029/256966655-80fe64f2-3735-4ba2-9f95-31bb40332ee5.png"> 用这个方案可以直接跳到指定行

哈哈，我知道，但要不影响之前的功能，我改造下即可

**Comment by baozouai** [comment]
@JiaErGen 试下0.4.0

https://github.com/baozouai/babel-plugin-enhance-log/releases/tag/v0.4.0

**Comment by JiaErGen** [comment]
> @JiaErGen试下0.4.0
> 
> https://github.com/baozouai/babel-plugin-enhance-log/releases/tag/v0.4.0

稳了
